### ISSUE TITLE
scout-boot-ui-dev causes spring injection to fail in scout classes

### ISSUE THREAD

**Issue by slevy85** [bsi-software/ScoutBoot#4]
Hi,

I have noticed that when the scout-boot-ui-dev jar is in the classpath, the injection doesn't work in scout pages, forms, outlines, etc.

To demonstrate it I have juste began the minimal archetype, added a @Service class (with its interface), add the @Inject on the service property in the HelloPage, and the application fails on runtime.

> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type '...'

This only happens if I launch the application in eclipse, if I launch the jar built by maven there is no problem, because of this plugin that removes the scout-ui-dev jar :
```
<plugin>  
	<groupId>org.springframework.boot</groupId>  
	<artifactId>spring-boot-maven-plugin</artifactId>  
	<executions>  
              <execution>  
			<goals>  
				<goal>repackage</goal>  
			</goals>  
		</execution>  
	</executions>  
	<configuration>  
		<excludeDevtools>true</excludeDevtools>  
		<excludeArtifactIds>scout-boot-ui-dev</excludeArtifactIds>  
	</configuration>  
</plugin>
```

**Comment by slevy85** [comment]
The issue is due to the `spring-boot-devtools` dependency. This tool will use two classloaders to restart the application, and scout beans are not in the restart classloader.
Information [here](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload).  

The solution is to have a `META-INF/spring-devtools.properties` that will include the scout classes in the restart classloader : `restart.include.scout=/org/eclipse/scout`.

**Comment by boardend** [comment]
Thanks for reporting this issue and providing the fix as pull request. I can confirm the issue and the working fix, so therefore I accepted your request.

Note: Maybe you have to add another spring-devtools.properties inside your project to include also your project beans.
